# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.1.1
_src_path: https://github.com/OCA/oca-addons-repo-template.git
dependency_installation_mode: OCA
generate_requirements_txt: false
include_wkhtmltopdf: true
odoo_version: 13.0
rebel_module_groups: []
repo_description: null
repo_name: stock-rma
repo_slug: https://github.com/ForgeFlow/stock-rma
travis_apt_packages: []
travis_apt_sources: []
