# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.17.1
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
generate_requirements_txt: false
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: false
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: true
odoo_test_flavor: Both
odoo_version: 16.0
org_name: ForgeFlow
org_slug: ForgeFlow
rebel_module_groups: []
repo_description: Return Merchandise Authorization for Odoo
repo_name: stock-rma
repo_slug: https://github.com/ForgeFlow/stock-rma
repo_website: https://github.com/ForgeFlow/stock-rma

