# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.3.5
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: false
include_wkhtmltopdf: true
odoo_version: 13.0
rebel_module_groups: []
repo_description: Manage returns authorizations
repo_name: stock-rma
repo_slug: https://github.com/ForgeFlow/stock-rma
travis_apt_packages: []
travis_apt_sources: []
